Spectrosopic Data Reduction: trace, extract, calibrate & data
astropy/astropy-tutorials pull request #511
Opened 2021-12-14 17:12 UTC by keflavich

Tutorial 3 following #508, #510

2022-01-04 17:20 UTC, adrn commented
I fixed the issues with the color-excess tutorial (causing your builds to fail), so if you rebase this and your other PRs (sorry...) the CI should start working again. Sorry for the headache!

2022-08-22 15:19 UTC, keflavich commented
I've addressed @eblur's comments and applied some other changes that were needed (header, import location, etc)

2022-08-24 18:35 UTC, kelle commented on tutorials/SpectroscopicDataReductionBasics/3-Trace_Extract_Wavelength-CalibrateSpectrum.ipynb
> +{
<p>cut "Part" from the title.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/astropy/astropy-tutorials/pull/511/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='0'/>

2022-08-24 18:35 UTC, kelle commented on tutorials/SpectroscopicDataReductionBasics/3-Trace_Extract_Wavelength-CalibrateSpectrum.ipynb
> +{
<p>gone through Spectroscopic Data Reduction 1 and 2 on finding the trace and wavelength calibration.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/astropy/astropy-tutorials/pull/511/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='1'/>

2022-08-24 18:35 UTC, kelle commented on tutorials/SpectroscopicDataReductionBasics/3-Trace_Extract_Wavelength-CalibrateSpectrum.ipynb
> +{
<p>link to docs https://docs.astropy.org/en/stable/units/equivalencies.html#spectral-doppler-equivalencies</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/astropy/astropy-tutorials/pull/511/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='37'/>

2022-08-24 18:35 UTC, kelle commented on tutorials/SpectroscopicDataReductionBasics/3-Trace_Extract_Wavelength-CalibrateSpectrum.ipynb
> +{
<p>Maybe open an issue on astropy-tutorials for a flux calibration tutorial and link to it here.</p><p>A tutorial on flux calibration is forthcoming (astropy-tutorials#570) </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/astropy/astropy-tutorials/pull/511/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='41'/>

2022-08-24 18:35 UTC, kelle requested changes
Teeny comments.

2022-08-24 19:00 UTC, kelle approved these changes

2022-08-24 19:03 UTC, merged